name: Build and Push Docker Image to Docker Hub

on: push
jobs:
  push_to_registry:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.LIAM_DOCKER_USERNAME }}
          password: ${{ secrets.WEBCOOS_DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: twlggles/webcooscamerafeatures:latest
