name: Build Docker Image

on:
  push:
    branches-ignore:
      - main

jobs:
  push_to_registry:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.LIAM_DOCKER_USERNAME }}
          password: ${{ secrets.WEBCOOS_DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: twlggles/webcooscamerafeatures:latest
